#!/bin/bash

# ==========================================
# Automated Nginx Setup for Shorthand Backend
# ==========================================
# This script automatically sets up Nginx reverse proxy configurations
# for Backend API, Grafana, Prometheus, and Loki with SSL certificates.
#
# Usage: sudo bash setup-nginx-monitoring.sh
#
# Features:
#   - Installs all required dependencies
#   - Creates Nginx config files if not present
#   - Sets up SSL certificates via Certbot
#   - Idempotent (safe to run multiple times)
#   - Detects backend port from docker-compose.prod.yml
# ==========================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get project root (parent of scripts directory)
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
NGINX_SITES_AVAILABLE="/etc/nginx/sites-available"
NGINX_SITES_ENABLED="/etc/nginx/sites-enabled"
BACKEND_DOMAIN="api.vikalpshorthand.com"
GRAFANA_DOMAIN="grafana.vikalpshorthand.com"
PROMETHEUS_DOMAIN="prometheus.vikalpshorthand.com"
LOKI_DOMAIN="loki.vikalpshorthand.com"

# Ports (will be auto-detected or can be overridden)
BACKEND_PORT="${BACKEND_PORT:-5001}"
GRAFANA_PORT="3001"
PROMETHEUS_PORT="9090"
LOKI_PORT="3100"

# Logging function
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# Install package if missing
install_if_missing() {
    local pkg="$1"
    if dpkg -s "$pkg" >/dev/null 2>&1; then
        log_success "$pkg is already installed"
        return 0
    else
        log_info "Installing $pkg..."
        apt-get install -y "$pkg" >/dev/null 2>&1
        log_success "$pkg installed"
    fi
}

# Detect backend port from docker-compose.prod.yml
detect_backend_port() {
    if [ -n "$BACKEND_PORT" ]; then
        log_info "Using configured backend port: $BACKEND_PORT"
        return
    fi

    if [ -f "$PROJECT_ROOT/docker-compose.prod.yml" ]; then
        # Try to extract port from docker-compose.prod.yml
        local detected_port=$(grep -A 5 "backend:" "$PROJECT_ROOT/docker-compose.prod.yml" | \
            grep "127.0.0.1:" | head -1 | sed -n 's/.*127\.0\.0\.1:\([0-9]*\):.*/\1/p')
        
        # Also check for PORT environment variable
        if [ -z "$detected_port" ]; then
            detected_port=$(grep -A 10 "backend:" "$PROJECT_ROOT/docker-compose.prod.yml" | \
                grep "PORT:" | head -1 | sed -n 's/.*PORT: *\([0-9]*\).*/\1/p')
        fi
        
        if [ -n "$detected_port" ]; then
            BACKEND_PORT="$detected_port"
            log_info "Detected backend port from docker-compose.prod.yml: $BACKEND_PORT"
            return
        fi
    fi

    # Check if backend is running and detect port
    if command -v docker >/dev/null 2>&1; then
        local running_port=$(docker ps --format "{{.Ports}}" | grep -oP '127\.0\.0\.1:\K[0-9]+(?=->5001)' | head -1)
        if [ -n "$running_port" ]; then
            BACKEND_PORT="$running_port"
            log_info "Detected backend port from running container: $BACKEND_PORT"
            return
        fi
    fi

    # Default fallback
    BACKEND_PORT="5001"
    log_warning "Could not detect backend port, using default: $BACKEND_PORT"
    log_warning "You can set BACKEND_PORT environment variable to override"
}

# Check if service is accessible on localhost
check_service_health() {
    local service_name="$1"
    local port="$2"
    local health_path="${3:-/}"
    
    log_info "Checking $service_name on port $port..."
    
    if curl -sf "http://127.0.0.1:$port$health_path" >/dev/null 2>&1; then
        log_success "$service_name is accessible on port $port"
        return 0
    else
        log_warning "$service_name is not accessible on port $port"
        log_warning "Make sure the service is running before continuing"
        return 1
    fi
}

# Create Nginx config file if it doesn't exist
create_nginx_config() {
    local domain="$1"
    local port="$2"
    local config_name="$3"
    local extra_config="${4:-}"
    
    local config_file="$NGINX_SITES_AVAILABLE/$domain"
    
    if [ -f "$config_file" ]; then
        log_warning "Nginx config for $domain already exists: $config_file"
        log_info "Skipping creation (to recreate, delete the file first)"
        return 0
    fi
    
    log_info "Creating Nginx config for $domain..."
    
    cat > "$config_file" <<EOF
# $config_name Nginx Configuration
# Domain: $domain
# Backend: http://127.0.0.1:$port
# Generated by setup-nginx-monitoring.sh

server {
    server_name $domain;

    location / {
        proxy_pass http://127.0.0.1:$port;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
$extra_config
    }

    listen 80;
}
EOF
    
    log_success "Created Nginx config: $config_file"
}

# Create backend API config
create_backend_config() {
    local domain="$BACKEND_DOMAIN"
    local port="$BACKEND_PORT"
    local config_file="$NGINX_SITES_AVAILABLE/$domain"
    
    if [ -f "$config_file" ]; then
        log_warning "Backend config already exists: $config_file"
        return 0
    fi
    
    log_info "Creating backend API Nginx config..."
    
    cat > "$config_file" <<EOF
# Backend API Nginx Configuration
# Domain: $domain
# Backend: http://127.0.0.1:$port
# Generated by setup-nginx-monitoring.sh

server {
    server_name $domain;

    location / {
        proxy_pass http://127.0.0.1:$port;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }

    listen 80;
}
EOF
    
    log_success "Created backend API config: $config_file"
}

# Create Grafana config
create_grafana_config() {
    local extra_config="        # WebSocket support for Grafana
        proxy_set_header Connection \"upgrade\";
        proxy_read_timeout 86400;"
    
    create_nginx_config "$GRAFANA_DOMAIN" "$GRAFANA_PORT" "Grafana" "$extra_config"
    
    # Add health check endpoint
    local config_file="$NGINX_SITES_AVAILABLE/$GRAFANA_DOMAIN"
    if [ -f "$config_file" ] && ! grep -q "/api/health" "$config_file"; then
        sed -i '/location \/ {/a\
\
    # Health check endpoint\
    location /api/health {\
        proxy_pass http://127.0.0.1:'"$GRAFANA_PORT"'/api/health;\
        access_log off;\
    }' "$config_file"
    fi
}

# Create Prometheus config
create_prometheus_config() {
    local extra_config="        # Prometheus specific settings
        proxy_read_timeout 300;
        proxy_connect_timeout 75;"
    
    create_nginx_config "$PROMETHEUS_DOMAIN" "$PROMETHEUS_PORT" "Prometheus" "$extra_config"
    
    # Add health check endpoint
    local config_file="$NGINX_SITES_AVAILABLE/$PROMETHEUS_DOMAIN"
    if [ -f "$config_file" ] && ! grep -q "/-/healthy" "$config_file"; then
        sed -i '/location \/ {/a\
\
    # Health check endpoint\
    location /-/healthy {\
        proxy_pass http://127.0.0.1:'"$PROMETHEUS_PORT"'/-/healthy;\
        access_log off;\
    }' "$config_file"
    fi
}

# Create Loki config
create_loki_config() {
    local extra_config="        # Loki specific settings
        proxy_read_timeout 300;
        proxy_connect_timeout 75;"
    
    create_nginx_config "$LOKI_DOMAIN" "$LOKI_PORT" "Loki" "$extra_config"
    
    # Add health check endpoint
    local config_file="$NGINX_SITES_AVAILABLE/$LOKI_DOMAIN"
    if [ -f "$config_file" ] && ! grep -q "/ready" "$config_file"; then
        sed -i '/location \/ {/a\
\
    # Health check endpoint\
    location /ready {\
        proxy_pass http://127.0.0.1:'"$LOKI_PORT"'/ready;\
        access_log off;\
    }' "$config_file"
    fi
}

# Enable Nginx site
enable_nginx_site() {
    local domain="$1"
    local config_file="$NGINX_SITES_AVAILABLE/$domain"
    local symlink="$NGINX_SITES_ENABLED/$domain"
    
    if [ ! -f "$config_file" ]; then
        log_error "Config file not found: $config_file"
        return 1
    fi
    
    if [ -L "$symlink" ]; then
        log_info "Site $domain is already enabled"
        return 0
    fi
    
    log_info "Enabling site: $domain"
    ln -sf "$config_file" "$symlink"
    log_success "Enabled site: $domain"
}

# Setup SSL certificate
setup_ssl_certificate() {
    local domain="$1"
    
    # Check if certificate already exists
    if [ -d "/etc/letsencrypt/live/$domain" ]; then
        log_info "SSL certificate for $domain already exists"
        log_info "To renew, run: sudo certbot renew"
        return 0
    fi
    
    log_info "Setting up SSL certificate for $domain..."
    log_warning "This will require DNS to be configured and port 80 to be accessible"
    
    # Check if domain resolves
    if ! host "$domain" >/dev/null 2>&1; then
        log_error "Domain $domain does not resolve. Please configure DNS first."
        return 1
    fi
    
    # Run certbot
    if certbot --nginx -d "$domain" --non-interactive --agree-tos --redirect; then
        log_success "SSL certificate installed for $domain"
    else
        log_error "Failed to install SSL certificate for $domain"
        log_warning "You may need to run manually: sudo certbot --nginx -d $domain"
        return 1
    fi
}

# Test Nginx configuration
test_nginx_config() {
    log_info "Testing Nginx configuration..."
    if nginx -t; then
        log_success "Nginx configuration is valid"
        return 0
    else
        log_error "Nginx configuration has errors"
        return 1
    fi
}

# Reload Nginx
reload_nginx() {
    log_info "Reloading Nginx..."
    if systemctl reload nginx; then
        log_success "Nginx reloaded successfully"
    else
        log_error "Failed to reload Nginx"
        return 1
    fi
}

# Main setup function
main() {
    echo ""
    echo -e "${GREEN}===========================================${NC}"
    echo -e "${GREEN}  Automated Nginx Setup Script${NC}"
    echo -e "${GREEN}  For Shorthand Backend & Monitoring${NC}"
    echo -e "${GREEN}===========================================${NC}"
    echo ""
    
    check_root
    
    log_info "Starting setup process..."
    echo ""
    
    # Step 1: Update system
    log_info "Step 1: Updating system packages..."
    apt-get update -y >/dev/null 2>&1
    log_success "System packages updated"
    echo ""
    
    # Step 2: Install dependencies
    log_info "Step 2: Installing required dependencies..."
    install_if_missing nginx
    install_if_missing certbot
    install_if_missing python3-certbot-nginx
    install_if_missing curl
    install_if_missing wget
    echo ""
    
    # Step 3: Ensure Nginx directories exist
    log_info "Step 3: Ensuring Nginx directories exist..."
    mkdir -p "$NGINX_SITES_AVAILABLE"
    mkdir -p "$NGINX_SITES_ENABLED"
    log_success "Nginx directories ready"
    echo ""
    
    # Step 4: Detect backend port
    log_info "Step 4: Detecting backend port..."
    detect_backend_port
    echo ""
    
    # Step 5: Check services (optional, non-blocking)
    log_info "Step 5: Checking service availability..."
    check_service_health "Backend API" "$BACKEND_PORT" "/" || true
    check_service_health "Grafana" "$GRAFANA_PORT" "/api/health" || true
    check_service_health "Prometheus" "$PROMETHEUS_PORT" "/-/healthy" || true
    check_service_health "Loki" "$LOKI_PORT" "/ready" || true
    echo ""
    
    # Step 6: Create Nginx configurations
    log_info "Step 6: Creating Nginx configurations..."
    create_backend_config
    create_grafana_config
    create_prometheus_config
    create_loki_config
    echo ""
    
    # Step 7: Enable sites
    log_info "Step 7: Enabling Nginx sites..."
    enable_nginx_site "$BACKEND_DOMAIN"
    enable_nginx_site "$GRAFANA_DOMAIN"
    enable_nginx_site "$PROMETHEUS_DOMAIN"
    enable_nginx_site "$LOKI_DOMAIN"
    echo ""
    
    # Step 8: Test Nginx configuration
    log_info "Step 8: Testing Nginx configuration..."
    if ! test_nginx_config; then
        log_error "Nginx configuration test failed. Please fix errors before continuing."
        exit 1
    fi
    echo ""
    
    # Step 9: Reload Nginx
    log_info "Step 9: Reloading Nginx..."
    reload_nginx
    echo ""
    
    # Step 10: Setup SSL certificates
    log_info "Step 10: Setting up SSL certificates..."
    log_warning "SSL certificate setup requires:"
    log_warning "  1. DNS records pointing to this server"
    log_warning "  2. Port 80 accessible from internet"
    log_warning "  3. Valid email for Let's Encrypt"
    echo ""
    
    read -p "Do you want to set up SSL certificates now? (y/n): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        setup_ssl_certificate "$BACKEND_DOMAIN" || true
        setup_ssl_certificate "$GRAFANA_DOMAIN" || true
        setup_ssl_certificate "$PROMETHEUS_DOMAIN" || true
        setup_ssl_certificate "$LOKI_DOMAIN" || true
        
        # Reload Nginx after SSL setup
        reload_nginx
    else
        log_info "Skipping SSL setup. You can run it later with:"
        log_info "  sudo certbot --nginx -d $BACKEND_DOMAIN"
        log_info "  sudo certbot --nginx -d $GRAFANA_DOMAIN"
        log_info "  sudo certbot --nginx -d $PROMETHEUS_DOMAIN"
        log_info "  sudo certbot --nginx -d $LOKI_DOMAIN"
    fi
    echo ""
    
    # Summary
    echo ""
    echo -e "${GREEN}===========================================${NC}"
    echo -e "${GREEN}  Setup Complete!${NC}"
    echo -e "${GREEN}===========================================${NC}"
    echo ""
    log_success "Nginx configurations created and enabled"
    echo ""
    echo "Access URLs (after SSL setup):"
    echo "  - Backend API:  https://$BACKEND_DOMAIN"
    echo "  - Grafana:      https://$GRAFANA_DOMAIN"
    echo "  - Prometheus:   https://$PROMETHEUS_DOMAIN"
    echo "  - Loki:         https://$LOKI_DOMAIN"
    echo ""
    echo "Next steps:"
    echo "  1. Ensure DNS records are configured"
    echo "  2. Run SSL setup if skipped: sudo certbot --nginx -d <domain>"
    echo "  3. Verify services are running: docker-compose -f docker-compose.prod.yml ps"
    echo "  4. Test access to each service"
    echo ""
}

# Run main function
main "$@"
